name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^10.0.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/general/1x/
    - assets/icons/general/2x/
    - assets/icons/general/3x/
    - assets/icons/selected/1x/
    - assets/icons/selected/2x/
    - assets/icons/selected/3x/
    - assets/icons/unSelected/1x/
    - assets/icons/unSelected/2x/
    - assets/icons/unSelected/3x/
    - assets/images/1x/
    - assets/images/2x/
    - assets/images/3x/
