name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^10.0.0
  google_fonts: ^8.2.1
  retrofit: ^4.10.0
  logger: ^2.6.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.0.1
  build_runner: ^2.6.0
  json_serializable: ^6.10.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/general/1x/
    - assets/icons/general/2x/
    - assets/icons/general/3x/
    - assets/icons/selected/1x/
    - assets/icons/selected/2x/
    - assets/icons/selected/3x/
    - assets/icons/unSelected/1x/
    - assets/icons/unSelected/2x/
    - assets/icons/unSelected/3x/
    - assets/images/1x/
    - assets/images/2x/
    - assets/images/3x/
